export default [
  {
    id: 0,
    title: "Product Page",
    image: "/Work-4.png",
    description: "Ecommerce Online Shop Iteractive Page",
    url: "https://msabdalaal.github.io/Ecommerce-Product-Page/",
    github: "https://github.com/msabdalaal/Ecommerce-Product-Page",
    bright: true,
  },
  {
    id: 1,
    title: "Interactive Card",
    image: "/Work-6.png",
    description: "Interactive Card Info Form",
    url: "https://msabdalaal.github.io//InteractiveInfoForm/",
    github: "https://github.com/msabdalaal/InteractiveInfoForm",
    bright: true,
  },
  {
    id: 2,
    title: "Calculator",
    image: "/Work-2.png",
    description: "Multitheme calculator App",
    url: "https://msabdalaal.github.io/calculator-app/",
    github: "https://github.com/msabdalaal/calculator-app",
    bright: false,
  },
  {
    id: 3,
    title: "Meme Generator",
    image: "/Work-7.png",
    description: "Meme Generator App With Adding Text",
    url: "https://msabdalaal.github.io/MemeGeneratorReact/",
    github: "https://github.com/msabdalaal/MemeGeneratorReact",
    bright: true,
  },
  {
    id: 4,
    title: "Rock Paper Scissors",
    image: "/Work-3.png",
    description: "Rock Paper Scissors Fun Game",
    url: "https://msabdalaal.github.io/rock-paper-scissors-master/",
    github: "https://github.com/msabdalaal/rock-paper-scissors-master",
    bright: false,
  },
  {
    id: 5,
    title: "Tenzies Game",
    image: "/Work-8.png",
    description: "Tenzies Game With Cool Winning Animation",
    url: "https://msabdalaal.github.io/TenziesGameReact/",
    github: "https://github.com/msabdalaal/TenziesGameReact",
    bright: true,
  },
  {
    id: 6,
    title: "ToDo",
    image: "/Work-1.png",
    description: "Todo List App",
    url: "https://msabdalaal.github.io/todo-app/",
    github: "https://github.com/msabdalaal/todo-app",
    bright: false,
  },
  {
    id: 7,
    title: "Quizzical",
    image: "/Work-5.png",
    description: "Trivia Quizz Game",
    url: "https://msabdalaal.github.io/Quizzical/",
    github: "https://github.com/msabdalaal/Quizzical",
    bright: true,
  },
  {
    id: 8,
    title: "IP Address Tracker",
    image: "/Work-9.jpg",
    description: "IP Address Tracker / search for any ip location",
    url: "https://msabdalaal.github.io/IP-Address-Tracker/",
    github: "https://github.com/msabdalaal/IP-Address-Tracker/",
    bright: true,
  },
  {
    id: 9,
    title: "REST Countries API",
    image: "/Work-10.jpg",
    description:
      "App gives you everything you need to know about all countries",
    url: "https://msabdalaal.github.io/REST-Countries-API/",
    github: "https://github.com/msabdalaal/REST-Countries-API",
    bright: true,
  },
  {
    id: 10,
    title: "Netflix Clone",
    image: "/Work-11.png",
    description: "A Responsive clone for Netflix Website",
    url: "https://msfakeflix.netlify.app/",
    github: "https://github.com/msabdalaal/Netflix-Clone",
    bright: true,
  },
  {
    id: 11,
    title: "Spotify Clone",
    image: "/Work-12.png",
    description: "A Responsive clone for Spotify Website",
    url: "https://spotify-msabdalaal.netlify.app/",
    github: "https://github.com/msabdalaal/Spotify-Clone",
    bright: true,
  },
];
