export default [
  {
    id: 0,
    title: "Quizzical",
    image: "../src/assets/Work-5.png",
    description: "Trivia Quizz Game",
    url: "https://msabdalaal.github.io/Quizzical/",
    github: "https://github.com/msabdalaal/Quizzical",
    bright: true,
  },
  {
    id: 1,
    title: "ToDo",
    image: "../src/assets/Work-1.png",
    description: "Todo List App",
    url: "https://msabdalaal.github.io/todo-app/",
    github: "https://github.com/msabdalaal/todo-app",
    bright: false,
  },
  {
    id: 2,
    title: "Tenzies Game",
    image: "../src/assets/Work-8.png",
    description: "Tenzies Game With Cool Winning Animation",
    url: "https://msabdalaal.github.io/TenziesGameReact/",
    github: "https://github.com/msabdalaal/TenziesGameReact",
    bright: true,
  },
  {
    id: 3,
    title: "Rock Paper Scissors",
    image: "../src/assets/Work-3.png",
    description: "Rock Paper Scissors Fun Game",
    url: "https://msabdalaal.github.io/rock-paper-scissors-master/",
    github: "https://github.com/msabdalaal/rock-paper-scissors-master",
    bright: false,
  },
  {
    id: 4,
    title: "Meme Generator",
    image: "../src/assets/Work-7.png",
    description: "Meme Generator App With Adding Text",
    url: "https://msabdalaal.github.io/MemeGeneratorReact/",
    github: "https://github.com/msabdalaal/MemeGeneratorReact",
    bright: true,
  },
  {
    id: 5,
    title: "Calculator",
    image: "../src/assets/Work-2.png",
    description: "Multitheme calculator App",
    url: "https://msabdalaal.github.io/calculator-app/",
    github: "https://github.com/msabdalaal/calculator-app",
    bright: false,
  },
  {
    id: 6,
    title: "Interactive Card",
    image: "../src/assets/Work-6.png",
    description: "Interactive Card Info Form",
    url: "https://msabdalaal.github.io//InteractiveInfoForm/",
    github: "https://github.com/msabdalaal/InteractiveInfoForm",
    bright: true,
  },
  {
    id: 7,
    title: "Product Page",
    image: "../src/assets/Work-4.png",
    description: "Ecommerce Online Shop Iteractive Page",
    url: "https://msabdalaal.github.io/Ecommerce-Product-Page/",
    github: "https://github.com/msabdalaal/Ecommerce-Product-Page",
    bright: true,
  },
];
